import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const hindSiliguri = Hind_Siliguri({
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "মেহেদি চাই!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" className={cn("font-sans", hindSiliguri.className, "dark")}>
      <body
        className={`antialiased relative min-h-screen bg-cover bg-center bg-no-repeat bg-fixed bg-[url('/bg.png')]`}
      >
        <div className="fixed inset-0 bg-background/95 overflow-y-auto">
          <div className="z-50 flex flex-col items-center justify-center container mx-auto w-full px-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
